<?php

namespace Database\Seeders;

use App\Models\POSHunter;
use Illuminate\Database\Seeder;

class POSHunterSentences extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $sentences = [
            ['difficulty' => 'easy', 'sentence' => 'The dog barked loudly.'],
            ['difficulty' => 'easy', 'sentence' => 'She drank water.'],
            ['difficulty' => 'easy', 'sentence' => 'He reads books daily.'],
            ['difficulty' => 'easy', 'sentence' => 'Birds fly high.'],
            ['difficulty' => 'easy', 'sentence' => 'The sun shines brightly.'],
            ['difficulty' => 'easy', 'sentence' => 'They play soccer.'],
            ['difficulty' => 'easy', 'sentence' => 'She likes flowers.'],
            ['difficulty' => 'easy', 'sentence' => 'The baby sleeps quietly.'],
            ['difficulty' => 'easy', 'sentence' => 'He eats apples.'],
            ['difficulty' => 'easy', 'sentence' => 'Fish swim in water.'],
            ['difficulty' => 'easy', 'sentence' => 'She sings beautifully.'],
            ['difficulty' => 'easy', 'sentence' => 'The wind blows softly.'],
            ['difficulty' => 'easy', 'sentence' => 'They watch movies.'],
            ['difficulty' => 'easy', 'sentence' => 'The cat sleeps often.'],
            ['difficulty' => 'easy', 'sentence' => 'She reads stories.'],
            ['difficulty' => 'easy', 'sentence' => 'The sky is blue.'],
            ['difficulty' => 'easy', 'sentence' => 'He walks daily.'],
            ['difficulty' => 'easy', 'sentence' => 'The trees are tall.'],
            ['difficulty' => 'easy', 'sentence' => 'They ride bikes.'],
            ['difficulty' => 'easy', 'sentence' => 'He plays guitar.'],
            ['difficulty' => 'easy', 'sentence' => 'She swims fast.'],
            ['difficulty' => 'easy', 'sentence' => 'The leaves are green.'],
            ['difficulty' => 'easy', 'sentence' => 'The dog wags its tail.'],
            ['difficulty' => 'easy', 'sentence' => 'She draws pictures.'],
            ['difficulty' => 'easy', 'sentence' => 'The car is red.'],
            ['difficulty' => 'easy', 'sentence' => 'They jump high.'],
            ['difficulty' => 'easy', 'sentence' => 'The cat purrs softly.'],
            ['difficulty' => 'easy', 'sentence' => 'He runs fast.'],
            ['difficulty' => 'easy', 'sentence' => 'She paints well.'],
            ['difficulty' => 'easy', 'sentence' => 'They laugh loudly.'],
            ['difficulty' => 'easy', 'sentence' => 'The cake smells good.'],
            ['difficulty' => 'easy', 'sentence' => 'She skips happily.'],
            ['difficulty' => 'easy', 'sentence' => 'He listens carefully.'],
            ['difficulty' => 'easy', 'sentence' => 'The grass is green.'],
            ['difficulty' => 'easy', 'sentence' => 'They clap loudly.'],
            ['difficulty' => 'easy', 'sentence' => 'The child smiles brightly.'],
            ['difficulty' => 'easy', 'sentence' => 'She dances gracefully.'],
            ['difficulty' => 'easy', 'sentence' => 'The door is open.'],
            ['difficulty' => 'easy', 'sentence' => 'They eat together.'],
            ['difficulty' => 'easy', 'sentence' => 'He laughs often.'],
            ['difficulty' => 'easy', 'sentence' => 'The book is old.'],
            ['difficulty' => 'easy', 'sentence' => 'She cooks dinner.'],
            ['difficulty' => 'easy', 'sentence' => 'The table is clean.'],
            ['difficulty' => 'easy', 'sentence' => 'They drive slowly.'],
            ['difficulty' => 'easy', 'sentence' => 'The bird sings sweetly.'],
            ['difficulty' => 'easy', 'sentence' => 'He talks calmly.'],
            ['difficulty' => 'easy', 'sentence' => 'She walks quickly.'],
            ['difficulty' => 'easy', 'sentence' => 'The fish are small.'],
            ['difficulty' => 'easy', 'sentence' => 'They dance together.'],
            ['difficulty' => 'easy', 'sentence' => 'He writes neatly.'],
            ['difficulty' => 'easy', 'sentence' => 'The house is big.'],
            ['difficulty' => 'easy', 'sentence' => 'She knits scarves.'],
            ['difficulty' => 'easy', 'sentence' => 'They talk softly.'],
            ['difficulty' => 'easy', 'sentence' => 'The chair is broken.'],
            ['difficulty' => 'easy', 'sentence' => 'She draws flowers.'],
            ['difficulty' => 'easy', 'sentence' => 'The apple is red.'],
            ['difficulty' => 'easy', 'sentence' => 'They hike often.'],
            ['difficulty' => 'easy', 'sentence' => 'He works hard.'],
            ['difficulty' => 'easy', 'sentence' => 'The boy is tall.'],
            ['difficulty' => 'easy', 'sentence' => 'She whispers softly.'],
            ['difficulty' => 'easy', 'sentence' => 'The cake is sweet.'],
            ['difficulty' => 'easy', 'sentence' => 'He listens quietly.'],
            ['difficulty' => 'easy', 'sentence' => 'They laugh together.'],
            ['difficulty' => 'easy', 'sentence' => 'The cat is soft.'],
            ['difficulty' => 'easy', 'sentence' => 'She bakes cookies.'],
            ['difficulty' => 'easy', 'sentence' => 'The dog is playful.'],
            ['difficulty' => 'easy', 'sentence' => 'They swim together.'],
            ['difficulty' => 'easy', 'sentence' => 'He cleans the car.'],
            ['difficulty' => 'easy', 'sentence' => 'The lamp is bright.'],
            ['difficulty' => 'easy', 'sentence' => 'She reads books.'],
            ['difficulty' => 'easy', 'sentence' => 'The soup is hot.'],
            ['difficulty' => 'easy', 'sentence' => 'He sings songs.'],
            ['difficulty' => 'easy', 'sentence' => 'The plant grows tall.'],
            ['difficulty' => 'easy', 'sentence' => 'She writes stories.'],
            ['difficulty' => 'easy', 'sentence' => 'The car is fast.'],
            ['difficulty' => 'easy', 'sentence' => 'They walk slowly.'],
            ['difficulty' => 'easy', 'sentence' => 'The flower smells nice.'],
            ['difficulty' => 'easy', 'sentence' => 'She knits blankets.'],
            ['difficulty' => 'easy', 'sentence' => 'The floor is clean.'],
            ['difficulty' => 'easy', 'sentence' => 'They laugh loudly.'],
            ['difficulty' => 'easy', 'sentence' => 'The room is dark.'],
            ['difficulty' => 'easy', 'sentence' => 'She dances well.'],
            ['difficulty' => 'easy', 'sentence' => 'He drinks milk.'],
            ['difficulty' => 'easy', 'sentence' => 'The tree is tall.'],
            ['difficulty' => 'easy', 'sentence' => 'She smiles brightly.'],
            ['difficulty' => 'easy', 'sentence' => 'The baby is asleep.'],
            ['difficulty' => 'easy', 'sentence' => 'He runs quickly.'],
            ['difficulty' => 'easy', 'sentence' => 'The boat floats.'],
            ['difficulty' => 'easy', 'sentence' => 'She draws animals.'],
            ['difficulty' => 'easy', 'sentence' => 'The snow is white.'],
            ['difficulty' => 'easy', 'sentence' => 'He likes movies.'],
            ['difficulty' => 'easy', 'sentence' => 'The cheese is tasty.'],
            ['difficulty' => 'easy', 'sentence' => 'She enjoys music.'],
            ['difficulty' => 'easy', 'sentence' => 'They eat pizza.'],
            ['difficulty' => 'easy', 'sentence' => 'The fire burns bright.'],
            ['difficulty' => 'easy', 'sentence' => 'He climbs trees.'],
            ['difficulty' => 'easy', 'sentence' => 'The sky is clear.'],
            ['difficulty' => 'easy', 'sentence' => 'She drives fast.'],
            ['difficulty' => 'easy', 'sentence' => 'The milk is cold.'],
            ['difficulty' => 'easy', 'sentence' => 'They watch sports.'],
            ['difficulty' => 'easy', 'sentence' => 'He draws cars.'],
            ['difficulty' => 'easy', 'sentence' => 'The cat is fluffy.'],
            ['difficulty' => 'medium', 'sentence' => 'The teacher explained the concept thoroughly.'],
            ['difficulty' => 'medium', 'sentence' => 'She quickly solved the complex math problem.'],
            ['difficulty' => 'medium', 'sentence' => 'The scientists conducted experiments to prove their theory.'],
            ['difficulty' => 'medium', 'sentence' => 'He carefully measured the ingredients for the recipe.'],
            ['difficulty' => 'medium', 'sentence' => 'The library was unusually quiet on Saturday.'],
            ['difficulty' => 'medium', 'sentence' => 'She hesitated briefly before answering the question.'],
            ['difficulty' => 'medium', 'sentence' => 'The students studied diligently for their exams.'],
            ['difficulty' => 'medium', 'sentence' => 'He skillfully painted the landscape.'],
            ['difficulty' => 'medium', 'sentence' => 'The athlete trained hard to improve his speed.'],
            ['difficulty' => 'medium', 'sentence' => 'They decided to hike despite the rainy forecast.'],
            ['difficulty' => 'medium', 'sentence' => 'The author wrote a compelling story about courage.'],
            ['difficulty' => 'medium', 'sentence' => 'She arranged the flowers beautifully in the vase.'],
            ['difficulty' => 'medium', 'sentence' => 'He spoke passionately about his ideas.'],
            ['difficulty' => 'medium', 'sentence' => 'The team worked together efficiently to meet the deadline.'],
            ['difficulty' => 'medium', 'sentence' => 'She observed the stars through her telescope.'],
            ['difficulty' => 'medium', 'sentence' => 'The engineer designed a bridge that would withstand strong winds.'],
            ['difficulty' => 'medium', 'sentence' => 'He whispered softly to avoid waking the baby.'],
            ['difficulty' => 'medium', 'sentence' => 'The artist sculpted a figure from a block of marble.'],
            ['difficulty' => 'medium', 'sentence' => 'She rearranged the furniture to make more space.'],
            ['difficulty' => 'medium', 'sentence' => 'The chef prepared a feast with fresh ingredients.'],
            ['difficulty' => 'medium', 'sentence' => 'They listened attentively to the lecture.'],
            ['difficulty' => 'medium', 'sentence' => 'The climbers reached the summit at dawn.'],
            ['difficulty' => 'medium', 'sentence' => 'She explained the rules before the game began.'],
            ['difficulty' => 'medium', 'sentence' => 'The doctor carefully examined the patient.'],
            ['difficulty' => 'medium', 'sentence' => 'The manager reviewed the reports thoroughly.'],
            ['difficulty' => 'medium', 'sentence' => 'He dedicated his life to studying marine biology.'],
            ['difficulty' => 'medium', 'sentence' => 'She shared a detailed plan with the committee.'],
            ['difficulty' => 'medium', 'sentence' => 'The musicians played harmoniously together.'],
            ['difficulty' => 'medium', 'sentence' => 'He took notes diligently during the lecture.'],
            ['difficulty' => 'medium', 'sentence' => 'The gardener planted flowers around the yard.'],
            ['difficulty' => 'medium', 'sentence' => 'She taught the children how to bake cookies.'],
            ['difficulty' => 'medium', 'sentence' => 'The detective solved the case by examining clues.'],
            ['difficulty' => 'medium', 'sentence' => 'They hosted a party to celebrate the occasion.'],
            ['difficulty' => 'medium', 'sentence' => 'The team developed a strategy to win the game.'],
            ['difficulty' => 'medium', 'sentence' => 'She wrote a report summarizing the findings.'],
            ['difficulty' => 'medium', 'sentence' => 'The librarian organized the books by genre.'],
            ['difficulty' => 'medium', 'sentence' => 'He inspected the machinery for any issues.'],
            ['difficulty' => 'medium', 'sentence' => 'The architect designed a modern building.'],
            ['difficulty' => 'medium', 'sentence' => 'She presented a persuasive argument.'],
            ['difficulty' => 'medium', 'sentence' => 'The dog barked loudly at strangers.'],
            ['difficulty' => 'medium', 'sentence' => 'He applied for a job at a tech company.'],
            ['difficulty' => 'medium', 'sentence' => 'The chef sliced the vegetables thinly.'],
            ['difficulty' => 'medium', 'sentence' => 'They participated actively in the discussion.'],
            ['difficulty' => 'medium', 'sentence' => 'The professor lectured on complex topics.'],
            ['difficulty' => 'medium', 'sentence' => 'He constructed a model airplane from scratch.'],
            ['difficulty' => 'medium', 'sentence' => 'She suggested a plan to increase productivity.'],
            ['difficulty' => 'medium', 'sentence' => 'The crowd cheered enthusiastically at the game.'],
            ['difficulty' => 'medium', 'sentence' => 'He read a book about historical events.'],
            ['difficulty' => 'medium', 'sentence' => 'The scientist published a study on climate change.'],
            ['difficulty' => 'medium', 'sentence' => 'She danced gracefully across the stage.'],
            ['difficulty' => 'medium', 'sentence' => 'The pilot navigated through turbulent skies.'],
            ['difficulty' => 'medium', 'sentence' => 'He repaired the car’s engine himself.'],
            ['difficulty' => 'medium', 'sentence' => 'The doctor performed a successful surgery.'],
            ['difficulty' => 'medium', 'sentence' => 'She folded the clothes neatly.'],
            ['difficulty' => 'medium', 'sentence' => 'The firefighters responded quickly to the alarm.'],
            ['difficulty' => 'medium', 'sentence' => 'The children laughed happily at the playground.'],
            ['difficulty' => 'medium', 'sentence' => 'He recommended a book to his friend.'],
            ['difficulty' => 'medium', 'sentence' => 'The driver navigated the road cautiously.'],
            ['difficulty' => 'medium', 'sentence' => 'The musician tuned his guitar carefully.'],
            ['difficulty' => 'medium', 'sentence' => 'The chef cooked the steak to perfection.'],
            ['difficulty' => 'medium', 'sentence' => 'She organized the files in alphabetical order.'],
            ['difficulty' => 'medium', 'sentence' => 'The runner trained daily for the marathon.'],
            ['difficulty' => 'medium', 'sentence' => 'They saved money for their vacation.'],
            ['difficulty' => 'medium', 'sentence' => 'The teacher praised the student’s efforts.'],
            ['difficulty' => 'medium', 'sentence' => 'He drove the car smoothly around the curve.'],
            ['difficulty' => 'medium', 'sentence' => 'The police officer directed traffic at the intersection.'],
            ['difficulty' => 'medium', 'sentence' => 'She jogged through the park every morning.'],
            ['difficulty' => 'medium', 'sentence' => 'The team analyzed the data thoroughly.'],
            ['difficulty' => 'medium', 'sentence' => 'He played the guitar passionately.'],
            ['difficulty' => 'medium', 'sentence' => 'The company launched a new product.'],
            ['difficulty' => 'medium', 'sentence' => 'The journalist interviewed the author.'],
            ['difficulty' => 'medium', 'sentence' => 'She brainstormed ideas for her project.'],
            ['difficulty' => 'medium', 'sentence' => 'The artist displayed his work at the gallery.'],
            ['difficulty' => 'medium', 'sentence' => 'The student wrote a detailed essay.'],
            ['difficulty' => 'medium', 'sentence' => 'The programmer created a new software application.'],
            ['difficulty' => 'medium', 'sentence' => 'He discussed his plans for the future.'],
            ['difficulty' => 'medium', 'sentence' => 'The patient followed the doctor’s instructions.'],
            ['difficulty' => 'medium', 'sentence' => 'She purchased a ticket for the concert.'],
            ['difficulty' => 'medium', 'sentence' => 'The gardener watered the plants every morning.'],
            ['difficulty' => 'medium', 'sentence' => 'The child assembled the puzzle with ease.'],
            ['difficulty' => 'medium', 'sentence' => 'The chef seasoned the dish with spices.'],
            ['difficulty' => 'medium', 'sentence' => 'He shared his experiences with the group.'],
            ['difficulty' => 'medium', 'sentence' => 'She donated books to the library.'],
            ['difficulty' => 'medium', 'sentence' => 'The explorer discovered a hidden cave.'],
            ['difficulty' => 'medium', 'sentence' => 'The professor analyzed historical documents.'],
            ['difficulty' => 'medium', 'sentence' => 'She painted a beautiful landscape.'],
            ['difficulty' => 'medium', 'sentence' => 'The musician practiced the piano for hours.'],
            ['difficulty' => 'medium', 'sentence' => 'The detective solved the mystery quickly.'],
            ['difficulty' => 'medium', 'sentence' => 'The pilot checked the instruments before takeoff.'],
            ['difficulty' => 'medium', 'sentence' => 'He explained the topic in great detail.'],
            ['difficulty' => 'medium', 'sentence' => 'The nurse cared for the patients gently.'],
            ['difficulty' => 'medium', 'sentence' => 'The coach motivated the team before the game.'],
            ['difficulty' => 'medium', 'sentence' => 'She admired the view from the mountain peak.'],
            ['difficulty' => 'hard', 'sentence' => 'Despite the arduous climb, they reached the summit in the face of harsh conditions.'],
            ['difficulty' => 'hard', 'sentence' => 'The scientist meticulously recorded the experimental data for further analysis.'],
            ['difficulty' => 'hard', 'sentence' => 'After a lengthy debate, the committee decided to implement stricter policies.'],
            ['difficulty' => 'hard', 'sentence' => 'With an unwavering dedication, she pursued her dreams despite numerous setbacks.'],
            ['difficulty' => 'hard', 'sentence' => 'The detective pieced together the clues to reveal an intricate conspiracy.'],
            ['difficulty' => 'hard', 'sentence' => 'Though the journey was fraught with peril, they remained resolute in their mission.'],
            ['difficulty' => 'hard', 'sentence' => 'The council convened to discuss reforms on environmental regulations.'],
            ['difficulty' => 'hard', 'sentence' => 'The historian uncovered ancient manuscripts that shed light on past civilizations.'],
            ['difficulty' => 'hard', 'sentence' => 'Undeterred by the complexity, the team devised a sophisticated solution.'],
            ['difficulty' => 'hard', 'sentence' => 'After extensive research, the biologists discovered a previously unknown species.'],
            ['difficulty' => 'hard', 'sentence' => 'With a calculated approach, the investor diversified her portfolio strategically.'],
            ['difficulty' => 'hard', 'sentence' => 'The architect designed a building that blended modern and traditional aesthetics.'],
            ['difficulty' => 'hard', 'sentence' => 'Although the project faced multiple delays, it was completed successfully.'],
            ['difficulty' => 'hard', 'sentence' => 'With limited resources, the explorer survived by utilizing his ingenuity.'],
            ['difficulty' => 'hard', 'sentence' => 'The novel explored complex themes of identity, culture, and societal expectations.'],
            ['difficulty' => 'hard', 'sentence' => 'The lecturer presented an intricate theory on quantum mechanics.'],
            ['difficulty' => 'hard', 'sentence' => 'Despite the political upheaval, the organization continued its humanitarian work.'],
            ['difficulty' => 'hard', 'sentence' => 'With unparalleled precision, the surgeon performed the complex procedure.'],
            ['difficulty' => 'hard', 'sentence' => 'The experiment required meticulous attention to each variable.'],
            ['difficulty' => 'hard', 'sentence' => 'The committee revised the guidelines to reflect recent technological advancements.'],
            ['difficulty' => 'hard', 'sentence' => 'She articulated her stance eloquently, winning over the skeptical audience.'],
            ['difficulty' => 'hard', 'sentence' => 'The analysis revealed a correlation between environmental changes and species behavior.'],
            ['difficulty' => 'hard', 'sentence' => 'The psychologist examined how cultural factors influence individual behavior.'],
            ['difficulty' => 'hard', 'sentence' => 'The diplomat skillfully negotiated the terms of the treaty.'],
            ['difficulty' => 'hard', 'sentence' => 'Despite the intricacies involved, they constructed the device as planned.'],
            ['difficulty' => 'hard', 'sentence' => 'The athlete trained rigorously, pushing her limits in preparation for the competition.'],
            ['difficulty' => 'hard', 'sentence' => 'The botanist cataloged an extensive range of flora native to the region.'],
            ['difficulty' => 'hard', 'sentence' => 'The inventor patented a groundbreaking method for renewable energy.'],
            ['difficulty' => 'hard', 'sentence' => 'The lawyer prepared a detailed case study, highlighting key precedents.'],
            ['difficulty' => 'hard', 'sentence' => 'The musician composed a symphony that expressed a range of human emotions.'],
            ['difficulty' => 'hard', 'sentence' => 'The economist presented a report on the implications of global trade policies.'],
            ['difficulty' => 'hard', 'sentence' => 'In a thought-provoking essay, the author challenged prevailing societal norms.'],
            ['difficulty' => 'hard', 'sentence' => 'The committee deliberated extensively before reaching a unanimous decision.'],
            ['difficulty' => 'hard', 'sentence' => 'The professor assigned a project that required advanced statistical analysis.'],
            ['difficulty' => 'hard', 'sentence' => 'The engineer designed a sustainable solution to reduce carbon emissions.'],
            ['difficulty' => 'hard', 'sentence' => 'The exhibit featured artifacts that were intricately carved by ancient artisans.'],
            ['difficulty' => 'hard', 'sentence' => 'With detailed observations, the ecologist documented animal migration patterns.'],
            ['difficulty' => 'hard', 'sentence' => 'The mathematician solved the equation by applying a series of complex theorems.'],
            ['difficulty' => 'hard', 'sentence' => 'Though faced with adversity, she continued her work with an indomitable spirit.'],
            ['difficulty' => 'hard', 'sentence' => 'The art critic analyzed the symbolism in the painter’s abstract work.'],
            ['difficulty' => 'hard', 'sentence' => 'The explorer ventured into uncharted territories to map the landscape.'],
            ['difficulty' => 'hard', 'sentence' => 'With a keen understanding of law, the judge delivered a fair ruling.'],
            ['difficulty' => 'hard', 'sentence' => 'The debate highlighted opposing views on the effects of globalization.'],
            ['difficulty' => 'hard', 'sentence' => 'After a lengthy negotiation, the parties reached a tentative agreement.'],
            ['difficulty' => 'hard', 'sentence' => 'The surgeon demonstrated remarkable dexterity in the operating room.'],
            ['difficulty' => 'hard', 'sentence' => 'The astronaut completed rigorous training before embarking on the mission.'],
            ['difficulty' => 'hard', 'sentence' => 'The engineer incorporated eco-friendly materials in the construction project.'],
            ['difficulty' => 'hard', 'sentence' => 'The researcher collected comprehensive data on the effects of pollution.'],
            ['difficulty' => 'hard', 'sentence' => 'Despite its complexity, the puzzle was solved with logical reasoning.'],
            ['difficulty' => 'hard', 'sentence' => 'The professor presented a lecture on the ethical implications of AI.'],
            ['difficulty' => 'hard', 'sentence' => 'The policy aims to address systemic issues within the healthcare sector.'],
            ['difficulty' => 'hard', 'sentence' => 'The author delved into the psychological dimensions of her characters.'],
            ['difficulty' => 'hard', 'sentence' => 'The environmentalist advocated for stronger conservation efforts.'],
            ['difficulty' => 'hard', 'sentence' => 'The athlete’s dedication to his craft was evident in his performance.'],
            ['difficulty' => 'hard', 'sentence' => 'The debate centered around the philosophical concept of free will.'],
            ['difficulty' => 'hard', 'sentence' => 'In the financial sector, risk management is of paramount importance.'],
            ['difficulty' => 'hard', 'sentence' => 'The biographer meticulously chronicled the subject’s life journey.'],
            ['difficulty' => 'hard', 'sentence' => 'The architect faced challenges in designing the skyscraper.'],
            ['difficulty' => 'hard', 'sentence' => 'The novelist’s prose is imbued with a poetic quality that captivates readers.'],
            ['difficulty' => 'hard', 'sentence' => 'The environmentalist proposed sustainable alternatives to waste management.'],
            ['difficulty' => 'hard', 'sentence' => 'Through various trials, the inventor perfected his innovative device.'],
            ['difficulty' => 'hard', 'sentence' => 'The botanist noted that the plant species was resistant to certain climates.'],
            ['difficulty' => 'hard', 'sentence' => 'The conversation explored profound questions about existence.'],
            ['difficulty' => 'hard', 'sentence' => 'The journal published a groundbreaking study on neurological patterns.'],
            ['difficulty' => 'hard', 'sentence' => 'The philosopher’s works remain influential in contemporary discourse.'],
            ['difficulty' => 'hard', 'sentence' => 'The artisan crafted a vase with intricate designs and vivid colors.'],
            ['difficulty' => 'hard', 'sentence' => 'The speech resonated with listeners, sparking thoughtful reflection.'],
            ['difficulty' => 'hard', 'sentence' => 'The company’s growth strategy emphasized sustainable practices.'],
            ['difficulty' => 'hard', 'sentence' => 'The debate addressed the ethical concerns of genetic engineering.'],
            ['difficulty' => 'hard', 'sentence' => 'The composer’s symphony was hailed as a masterpiece of modern music.'],
            ['difficulty' => 'hard', 'sentence' => 'The mountaineers braved the harsh elements on their ascent.'],
            ['difficulty' => 'hard', 'sentence' => 'The university hosted a symposium on climate science.'],
            ['difficulty' => 'hard', 'sentence' => 'The choreographer’s work displayed a seamless blend of tradition and innovation.'],
            ['difficulty' => 'hard', 'sentence' => 'The linguist studied the evolution of language over centuries.'],
            ['difficulty' => 'hard', 'sentence' => 'With her analytical mind, she solved the logic puzzle swiftly.'],
            ['difficulty' => 'hard', 'sentence' => 'The product launch drew attention from international media.'],
            ['difficulty' => 'hard', 'sentence' => 'The patient exhibited a remarkable recovery after treatment.'],
            ['difficulty' => 'hard', 'sentence' => 'The politician addressed key economic issues in his speech.'],
            ['difficulty' => 'hard', 'sentence' => 'The author researched historical events to add depth to her novel.'],
            ['difficulty' => 'hard', 'sentence' => 'The economist forecasted trends based on complex algorithms.'],
        ];
        foreach ($sentences as $sentence) {
            POSHunter::create($sentence);
        }

    }
}
