<?php

namespace Database\Seeders;

use App\Models\SentenceBuilder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class SentenceBuilderSentences extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $sentences = [
            ['difficulty' => 'easy', 'sentence' => 'The boys played soccer in the park.'],
            ['difficulty' => 'easy', 'sentence' => 'The apples are red and green.'],
            ['difficulty' => 'easy', 'sentence' => 'She has two dogs at home.'],
            ['difficulty' => 'easy', 'sentence' => 'I bought three books yesterday.'],
            ['difficulty' => 'easy', 'sentence' => 'The birds are flying in the sky.'],
            ['difficulty' => 'easy', 'sentence' => 'He enjoys reading magazines in his free time.'],
            ['difficulty' => 'easy', 'sentence' => 'The teachers gave the students homework.'],
            ['difficulty' => 'easy', 'sentence' => 'They ate sandwiches for lunch.'],
            ['difficulty' => 'easy', 'sentence' => 'The children are playing outside.'],
            ['difficulty' => 'easy', 'sentence' => 'I see many cars in the parking lot.'],
            ['difficulty' => 'easy', 'sentence' => 'She has two sisters and one brother.'],
            ['difficulty' => 'easy', 'sentence' => 'The flowers in the garden are blooming.'],
            ['difficulty' => 'easy', 'sentence' => 'We went to the zoo last weekend.'],
            ['difficulty' => 'easy', 'sentence' => 'The kids are excited for the field trip.'],
            ['difficulty' => 'easy', 'sentence' => 'He likes to collect stamps and coins.'],
            ['difficulty' => 'easy', 'sentence' => 'The cookies were fresh and warm.'],
            ['difficulty' => 'easy', 'sentence' => 'They walked to the park after school.'],
            ['difficulty' => 'easy', 'sentence' => 'The cars are parked outside the building.'],
            ['difficulty' => 'easy', 'sentence' => 'She gave me three pencils and a notebook.'],
            ['difficulty' => 'easy', 'sentence' => 'The students read their books quietly.'],
            ['difficulty' => 'easy', 'sentence' => 'The teacher is writing on the whiteboard.'],
            ['difficulty' => 'easy', 'sentence' => 'The dogs are barking loudly in the yard.'],
            ['difficulty' => 'easy', 'sentence' => 'We are learning new words in class.'],
            ['difficulty' => 'easy', 'sentence' => 'He is wearing a blue jacket and black shoes.'],
            ['difficulty' => 'easy', 'sentence' => 'The shops were closed on Sunday.'],
            ['difficulty' => 'easy', 'sentence' => 'The teacher helped the students with their homework.'],
            ['difficulty' => 'easy', 'sentence' => 'The leaves are falling from the trees.'],
            ['difficulty' => 'easy', 'sentence' => 'I found my shoes under the bed.'],
            ['difficulty' => 'easy', 'sentence' => 'The apples are ripe and ready to pick.'],
            ['difficulty' => 'easy', 'sentence' => 'We had lunch at a new restaurant.'],
            ['difficulty' => 'easy', 'sentence' => 'He enjoys playing games with his friends.'],
            ['difficulty' => 'easy', 'sentence' => 'The windows are open, and the breeze is nice.'],
            ['difficulty' => 'easy', 'sentence' => 'The boys are playing basketball in the gym.'],
            ['difficulty' => 'easy', 'sentence' => 'I bought some new shoes yesterday.'],
            ['difficulty' => 'easy', 'sentence' => 'She has a collection of beautiful stamps.'],
            ['difficulty' => 'easy', 'sentence' => 'The children were excited about the upcoming trip.'],
            ['difficulty' => 'easy', 'sentence' => 'I saw five birds flying in the sky.'],
            ['difficulty' => 'easy', 'sentence' => 'The dog is barking at the mailman.'],
            ['difficulty' => 'easy', 'sentence' => 'She brought her lunch to school today.'],
            ['difficulty' => 'easy', 'sentence' => 'The students wrote their essays in class.'],
            ['difficulty' => 'easy', 'sentence' => 'We visited our grandparents last weekend.'],
            ['difficulty' => 'easy', 'sentence' => 'The flowers in the vase are beautiful.'],
            ['difficulty' => 'easy', 'sentence' => 'He wore his new shoes to the party.'],
            ['difficulty' => 'easy', 'sentence' => 'The cats are sleeping on the couch.'],
            ['difficulty' => 'easy', 'sentence' => 'The teacher explained the lesson clearly.'],
            ['difficulty' => 'easy', 'sentence' => 'I have two bikes in my garage.'],
            ['difficulty' => 'easy', 'sentence' => 'The dog chased the ball across the yard.'],
            ['difficulty' => 'easy', 'sentence' => 'She eats apples every day.'],
            ['difficulty' => 'easy', 'sentence' => 'The students listened carefully to the instructions.'],
            ['difficulty' => 'easy', 'sentence' => 'We took a walk in the park, and we saw a squirrel.'],
            ['difficulty' => 'easy', 'sentence' => 'The children played with their toys all afternoon.'],
            ['difficulty' => 'easy', 'sentence' => 'The birds are singing in the trees.'],
            ['difficulty' => 'easy', 'sentence' => 'I bought a new jacket for winter.'],
            ['difficulty' => 'easy', 'sentence' => 'The flowers smell sweet and fragrant.'],
            ['difficulty' => 'easy', 'sentence' => 'The ice cream was delicious, and it melted quickly.'],
            ['difficulty' => 'easy', 'sentence' => 'They are watching a movie at home.'],
            ['difficulty' => 'easy', 'sentence' => 'I have three siblings and a dog.'],
            ['difficulty' => 'easy', 'sentence' => 'The students finished their homework early.'],
            ['difficulty' => 'easy', 'sentence' => 'He is reading a book about history.'],
            ['difficulty' => 'easy', 'sentence' => 'The teachers were preparing for the school event.'],
            ['difficulty' => 'easy', 'sentence' => 'The car stopped at the red light.'],
            ['difficulty' => 'easy', 'sentence' => 'The house is clean and tidy.'],
            ['difficulty' => 'easy', 'sentence' => 'The girls are playing hopscotch on the sidewalk.'],
            ['difficulty' => 'easy', 'sentence' => 'She has a lot of friends at school.'],
            ['difficulty' => 'easy', 'sentence' => 'The books are on the table.'],
            ['difficulty' => 'easy', 'sentence' => 'He plays the guitar in a band.'],
            ['difficulty' => 'easy', 'sentence' => 'The dogs are running in the yard.'],
            ['difficulty' => 'easy', 'sentence' => 'I have two tickets for the concert.'],
            ['difficulty' => 'easy', 'sentence' => 'The students are excited for the school play.'],
            ['difficulty' => 'easy', 'sentence' => 'She wore a beautiful red dress to the party.'],
            ['difficulty' => 'easy', 'sentence' => 'The children made a snowman in the yard.'],
            ['difficulty' => 'easy', 'sentence' => 'I packed a lunch for work today.'],
            ['difficulty' => 'easy', 'sentence' => 'We saw many fish swimming in the aquarium.'],
            ['difficulty' => 'easy', 'sentence' => 'The kids are drawing pictures on the sidewalk.'],
            ['difficulty' => 'easy', 'sentence' => 'I need to buy groceries after work.'],
            ['difficulty' => 'easy', 'sentence' => 'The dog is wagging its tail.'],
            ['difficulty' => 'easy', 'sentence' => 'She wears glasses to read.'],
            ['difficulty' => 'easy', 'sentence' => 'We celebrated his birthday at home.'],
            ['difficulty' => 'easy', 'sentence' => 'The books are arranged neatly on the shelf.'],
            ['difficulty' => 'easy', 'sentence' => 'She likes to swim in the pool during the summer.'],
            ['difficulty' => 'easy', 'sentence' => 'The family went on vacation to the beach.'],
            ['difficulty' => 'easy', 'sentence' => 'I found some old photographs in the attic.'],
            ['difficulty' => 'easy', 'sentence' => 'He rode his bike to school today.'],
            ['difficulty' => 'easy', 'sentence' => 'The kids made a mess in the kitchen.'],
            ['difficulty' => 'easy', 'sentence' => 'I took a nap after lunch.'],
            ['difficulty' => 'easy', 'sentence' => 'The ice cream melted quickly in the sun.'],
            ['difficulty' => 'easy', 'sentence' => 'We need more pencils for the classroom.'],
            ['difficulty' => 'easy', 'sentence' => 'The snow is falling softly outside.'],
            ['difficulty' => 'easy', 'sentence' => 'She played the piano at the concert.'],
            ['difficulty' => 'easy', 'sentence' => 'The sky is blue and clear today.'],
            ['difficulty' => 'easy', 'sentence' => 'I bought a new pair of shoes for the party.'],
            ['difficulty' => 'easy', 'sentence' => 'The dogs bark loudly at the neighbors.'],
            ['difficulty' => 'easy', 'sentence' => 'The birds chirp every morning.'],
            ['difficulty' => 'easy', 'sentence' => 'The children decorated the tree with ornaments.'],
            ['difficulty' => 'easy', 'sentence' => 'We will go for a walk after dinner.'],
            ['difficulty' => 'easy', 'sentence' => 'He asked for help with his homework.'],
            ['difficulty' => 'easy', 'sentence' => 'The apples are fresh and crunchy.'],
            ['difficulty' => 'easy', 'sentence' => 'The teacher gave us new assignments.'],
            ['difficulty' => 'easy', 'sentence' => 'I like to play soccer with my friends.'],
            ['difficulty' => 'easy', 'sentence' => 'She finished her lunch early today.'],
            ['difficulty' => 'easy', 'sentence' => 'The kids are building a fort in the living room.'],
            ['difficulty' => 'easy', 'sentence' => 'We went on a hike in the mountains.'],
            ['difficulty' => 'easy', 'sentence' => 'He is painting a picture of a sunset.'],
            ['difficulty' => 'easy', 'sentence' => 'The dog chased after the ball.'],
            ['difficulty' => 'easy', 'sentence' => 'The teacher handed out the test papers.'],
            ['difficulty' => 'easy', 'sentence' => 'She likes to listen to music while working.'],
            ['difficulty' => 'easy', 'sentence' => 'The boy is riding his bike down the street.'],
            ['difficulty' => 'easy', 'sentence' => 'The children built a sandcastle at the beach.'],
            ['difficulty' => 'easy', 'sentence' => 'We went to the movies on Friday night.'],
            ['difficulty' => 'easy', 'sentence' => 'He reads books before going to bed.'],
            ['difficulty' => 'easy', 'sentence' => 'The sun is shining brightly today.'],
            ['difficulty' => 'easy', 'sentence' => 'I took a photo of the beautiful flowers.'],
            ['difficulty' => 'easy', 'sentence' => 'The students are learning about animals in class.'],
            ['difficulty' => 'medium', 'sentence' => 'The sun set behind the mountains, casting a beautiful orange glow.'],
            ['difficulty' => 'medium', 'sentence' => 'He quickly finished his homework, and then he went out to play.'],
            ['difficulty' => 'medium', 'sentence' => 'She wore a red dress, which was her favorite color, to the party.'],
            ['difficulty' => 'medium', 'sentence' => 'After the rain stopped, the children went outside to play.'],
            ['difficulty' => 'medium', 'sentence' => 'The students studied hard for their exams, but some were still nervous.'],
            ['difficulty' => 'medium', 'sentence' => 'I called her yesterday, but she didn’t pick up.'],
            ['difficulty' => 'medium', 'sentence' => 'The new movie was exciting, thrilling, and action-packed.'],
            ['difficulty' => 'medium', 'sentence' => 'He loves playing basketball, especially with his friends on weekends.'],
            ['difficulty' => 'medium', 'sentence' => 'My brother, who lives in New York, is coming to visit next week.'],
            ['difficulty' => 'medium', 'sentence' => 'She enjoys painting landscapes, which she finds relaxing, in her free time.'],
            ['difficulty' => 'medium', 'sentence' => 'The cake, decorated with colorful sprinkles, looked delicious.'],
            ['difficulty' => 'medium', 'sentence' => 'We took a walk in the park, admiring the flowers and trees along the way.'],
            ['difficulty' => 'medium', 'sentence' => 'He passed the test, although he was unsure about some of the questions.'],
            ['difficulty' => 'medium', 'sentence' => 'The concert was amazing, and the band played all of their hit songs.'],
            ['difficulty' => 'medium', 'sentence' => 'On his way home, he stopped at the store to buy some milk.'],
            ['difficulty' => 'medium', 'sentence' => 'The food at the restaurant was delicious, but the service was slow.'],
            ['difficulty' => 'medium', 'sentence' => 'They decided to take a road trip, but first, they needed to pack.'],
            ['difficulty' => 'medium', 'sentence' => 'I have a meeting at 10 AM, so I need to leave soon.'],
            ['difficulty' => 'medium', 'sentence' => 'After dinner, we went for a walk by the lake, enjoying the peaceful evening.'],
            ['difficulty' => 'medium', 'sentence' => 'The students, although tired, continued to work on their project.'],
            ['difficulty' => 'medium', 'sentence' => 'He was excited for the weekend, which would be filled with fun activities.'],
            ['difficulty' => 'medium', 'sentence' => 'I want to visit the museum, and then I’ll head to the park for a picnic.'],
            ['difficulty' => 'medium', 'sentence' => 'The book, which was on the shelf for months, is now being read by my sister.'],
            ['difficulty' => 'medium', 'sentence' => 'She wore a hat, which matched her dress perfectly, to the party.'],
            ['difficulty' => 'medium', 'sentence' => 'The dog ran across the yard, barking loudly as it chased the ball.'],
            ['difficulty' => 'medium', 'sentence' => 'They traveled to Paris, the city of love, to celebrate their anniversary.'],
            ['difficulty' => 'medium', 'sentence' => 'She asked me to come over for coffee, and I agreed right away.'],
            ['difficulty' => 'medium', 'sentence' => 'I cleaned my room, and then I organized my books on the shelf.'],
            ['difficulty' => 'medium', 'sentence' => 'The weather was cold, but it was still sunny outside.'],
            ['difficulty' => 'medium', 'sentence' => 'After lunch, we went to the beach, where we played volleyball.'],
            ['difficulty' => 'medium', 'sentence' => 'The children were tired, so they decided to take a nap.'],
            ['difficulty' => 'medium', 'sentence' => 'My friend loves playing the piano, but she’s learning how to play the guitar too.'],
            ['difficulty' => 'medium', 'sentence' => 'The car broke down on the way to the beach, and we had to call for help.'],
            ['difficulty' => 'medium', 'sentence' => 'We met at the coffee shop, where we discussed our plans for the weekend.'],
            ['difficulty' => 'medium', 'sentence' => 'The movie was long, but it was very entertaining.'],
            ['difficulty' => 'medium', 'sentence' => 'He looked out the window, watching the rain pour down.'],
            ['difficulty' => 'medium', 'sentence' => 'She finished her homework, then went out for a run.'],
            ['difficulty' => 'medium', 'sentence' => 'The teacher gave a long lecture, which I found very informative.'],
            ['difficulty' => 'medium', 'sentence' => 'He brought his favorite snacks, and we watched a movie together.'],
            ['difficulty' => 'medium', 'sentence' => 'The meeting was productive, but there were some issues to address later.'],
            ['difficulty' => 'medium', 'sentence' => 'We went to the store, bought some groceries, and then returned home.'],
            ['difficulty' => 'medium', 'sentence' => 'After the meeting, we went for lunch, and the food was great.'],
            ['difficulty' => 'medium', 'sentence' => 'The flowers, blooming in various colors, added beauty to the garden.'],
            ['difficulty' => 'medium', 'sentence' => 'She was reading a book, sipping her coffee, and enjoying the calm atmosphere.'],
            ['difficulty' => 'medium', 'sentence' => 'He traveled to many countries, learning about different cultures along the way.'],
            ['difficulty' => 'medium', 'sentence' => 'I don’t like coffee, but I love tea, especially green tea.'],
            ['difficulty' => 'medium', 'sentence' => 'The concert was amazing, with a light show and great music.'],
            ['difficulty' => 'medium', 'sentence' => 'I enjoy hiking on weekends, but I also like to relax at home.'],
            ['difficulty' => 'medium', 'sentence' => 'She likes to read novels, but her brother prefers comics.'],
            ['difficulty' => 'medium', 'sentence' => 'I bought a new phone, which is faster than my old one.'],
            ['difficulty' => 'medium', 'sentence' => 'We went hiking in the mountains, and the view was breathtaking.'],
            ['difficulty' => 'medium', 'sentence' => 'They decided to move to a new house, but it would take some time.'],
            ['difficulty' => 'medium', 'sentence' => 'She is learning French, although she already speaks Spanish fluently.'],
            ['difficulty' => 'medium', 'sentence' => 'I need to finish my homework, and then I can go out.'],
            ['difficulty' => 'medium', 'sentence' => 'The movie was exciting, and I couldn’t wait for the sequel.'],
            ['difficulty' => 'medium', 'sentence' => 'He likes playing soccer, but his favorite sport is basketball.'],
            ['difficulty' => 'medium', 'sentence' => 'I have to finish my project by Friday, so I’ll be busy this week.'],
            ['difficulty' => 'medium', 'sentence' => 'She likes chocolate cake, but she prefers vanilla ice cream.'],
            ['difficulty' => 'medium', 'sentence' => 'The meeting was interesting, and we discussed many important points.'],
            ['difficulty' => 'medium', 'sentence' => 'I enjoy listening to music, especially classical music, when I study.'],
            ['difficulty' => 'medium', 'sentence' => 'We went to the park, played football, and then had ice cream.'],
            ['difficulty' => 'medium', 'sentence' => 'She loves taking photos, and she has an amazing camera.'],
            ['difficulty' => 'medium', 'sentence' => 'The weather was warm, and the breeze was refreshing.'],
            ['difficulty' => 'medium', 'sentence' => 'They had a great time at the beach, swimming and playing volleyball.'],
            ['difficulty' => 'medium', 'sentence' => 'He finished his work early, so he went to the gym to exercise.'],
            ['difficulty' => 'medium', 'sentence' => 'We had a delicious dinner, and then we went for a walk.'],
            ['difficulty' => 'medium', 'sentence' => 'She loves reading novels, particularly fantasy stories.'],
            ['difficulty' => 'medium', 'sentence' => 'I went to the mall, but I didn’t find what I was looking for.'],
            ['difficulty' => 'medium', 'sentence' => 'We went to the movie theater, bought some popcorn, and found our seats.'],
            ['difficulty' => 'medium', 'sentence' => 'He is a talented musician, and he plays several instruments.'],
            ['difficulty' => 'medium', 'sentence' => 'They were talking about their plans for the weekend, laughing and joking.'],
            ['difficulty' => 'medium', 'sentence' => 'The garden, filled with colorful flowers, looked beautiful in the spring.'],
            ['difficulty' => 'medium', 'sentence' => 'I bought a new jacket, and it fits perfectly.'],
            ['difficulty' => 'medium', 'sentence' => 'She traveled to many places, including Paris, Rome, and New York.'],
            ['difficulty' => 'medium', 'sentence' => 'The books on the shelf, arranged neatly, looked inviting.'],
            ['difficulty' => 'medium', 'sentence' => 'We went for a drive, and the weather was perfect for it.'],
            ['difficulty' => 'medium', 'sentence' => 'She studied for hours, and she was ready for the test.'],
            ['difficulty' => 'medium', 'sentence' => 'After a long day, we went out to dinner, and then went home to sleep.'],
            ['difficulty' => 'medium', 'sentence' => 'I like reading books, but I also enjoy watching movies.'],
            ['difficulty' => 'medium', 'sentence' => 'They went to the zoo, and the children had a great time.'],
            ['difficulty' => 'medium', 'sentence' => 'She studied all night, preparing for the final exam.'],
            ['difficulty' => 'medium', 'sentence' => 'I don’t have time to go out, but I can meet you tomorrow.'],
            ['difficulty' => 'medium', 'sentence' => 'They bought a new house, which was much bigger than their old one.'],
            ['difficulty' => 'medium', 'sentence' => 'The weather was warm, and the sky was clear.'],
            ['difficulty' => 'medium', 'sentence' => 'We took a walk in the park, enjoying the sunshine.'],
            ['difficulty' => 'medium', 'sentence' => 'The dog barked loudly, but it didn’t stop wagging its tail.'],
            ['difficulty' => 'medium', 'sentence' => 'He took a nap in the afternoon, and he felt refreshed afterward.'],
            ['difficulty' => 'medium', 'sentence' => 'I went shopping for groceries, but I forgot to buy eggs.'],
            ['difficulty' => 'medium', 'sentence' => 'She loves gardening, and she spends every weekend in her garden.'],
            ['difficulty' => 'medium', 'sentence' => 'I like to swim in the pool, but I prefer the beach.'],
            ['difficulty' => 'medium', 'sentence' => 'He finished his homework quickly, and then he played video games.'],
            ['difficulty' => 'medium', 'sentence' => 'They decided to go hiking, but they weren’t sure about the weather.'],
            ['difficulty' => 'medium', 'sentence' => 'She called her friend to meet up, but she had to cancel last minute.'],
            ['difficulty' => 'medium', 'sentence' => 'I planned to bake a cake, but I ran out of sugar.'],
            ['difficulty' => 'medium', 'sentence' => 'The cat jumped onto the couch, and it immediately fell asleep.'],
            ['difficulty' => 'medium', 'sentence' => 'We enjoyed a delicious meal at the restaurant, but the service was slow.'],
            ['difficulty' => 'medium', 'sentence' => 'He likes to read books in the evening, and he always drinks tea while reading.'],
            ['difficulty' => 'medium', 'sentence' => 'I went for a jog this morning, and I felt great afterward.'],
            ['difficulty' => 'medium', 'sentence' => 'They took their car to the mechanic, but they still had to wait for repairs.'],
            ['difficulty' => 'medium', 'sentence' => 'The kids played outside all afternoon, and they were exhausted by evening.'],
            ['difficulty' => 'medium', 'sentence' => 'She met her colleague for lunch, and they had a nice conversation.'],
            ['difficulty' => 'medium', 'sentence' => 'He cleaned his room, and then he organized his bookshelves.'],
            ['difficulty' => 'medium', 'sentence' => 'They went to the museum, and they spent hours admiring the exhibits.'],
            ['difficulty' => 'medium', 'sentence' => 'I bought a new phone, and it has a lot of cool features.'],
            ['difficulty' => 'medium', 'sentence' => 'She was reading a book in the park, and a bird landed next to her.'],
            ['difficulty' => 'medium', 'sentence' => 'We visited the zoo, and the lion was the highlight of our trip.'],
            ['difficulty' => 'medium', 'sentence' => 'He was cooking dinner when his friend called, and they made plans to meet up.'],
            ['difficulty' => 'medium', 'sentence' => 'They were planning a trip to the beach, but the forecast predicted rain.'],
            ['difficulty' => 'medium', 'sentence' => 'I need to clean the house today, but I’m feeling too tired.'],
            ['difficulty' => 'medium', 'sentence' => 'She made a salad for lunch, and it was very refreshing.'],
            ['difficulty' => 'medium', 'sentence' => 'We decided to watch a movie, but the Wi-Fi was too slow to stream it.'],
            ['difficulty' => 'medium', 'sentence' => 'They invited their friends over for dinner, and they had a wonderful evening.'],
            ['difficulty' => 'medium', 'sentence' => 'I went to the gym in the morning, and then I had a healthy breakfast.'],
            ['difficulty' => 'medium', 'sentence' => 'She took a photo of the sunset, and it turned out to be beautiful.'],
            ['difficulty' => 'medium', 'sentence' => 'We bought new furniture for the living room, but it didn’t fit as expected.'],
            ['difficulty' => 'medium', 'sentence' => 'I enjoy hiking in the mountains, and I plan to go again this weekend.'],
            ['difficulty' => 'medium', 'sentence' => 'They were planning to go fishing, but the lake was too crowded.'],
            ['difficulty' => 'medium', 'sentence' => 'He played soccer with his friends, and then they went to get ice cream.'],
            ['difficulty' => 'medium', 'sentence' => 'I had a long day at work, but I was happy to relax at home afterward.'],
            ['difficulty' => 'medium', 'sentence' => 'She enjoys cooking, and she tries new recipes every week.'],
            ['difficulty' => 'medium', 'sentence' => 'We decided to go for a bike ride, but the road was too rough.'],
            ['difficulty' => 'medium', 'sentence' => 'They made plans for the weekend, but something unexpected came up.'],
            ['difficulty' => 'medium', 'sentence' => 'I wanted to try a new restaurant, but it was closed for renovations.'],
            ['difficulty' => 'medium', 'sentence' => 'She organized her desk, and now it looks much cleaner.'],
            ['difficulty' => 'medium', 'sentence' => 'They had a picnic in the park, and it was a perfect afternoon.'],
            ['difficulty' => 'medium', 'sentence' => 'He was reading a novel, but he kept getting distracted by the noise outside.'],
            ['difficulty' => 'medium', 'sentence' => 'We watched a soccer match on TV, but the game ended in a tie.'],
            ['difficulty' => 'medium', 'sentence' => 'I planned to study, but I ended up watching TV instead.'],
            ['difficulty' => 'medium', 'sentence' => 'She enjoyed a hot cup of coffee, and then she started working on her project.'],
            ['difficulty' => 'medium', 'sentence' => 'They spent the afternoon at the park, but they left when it started to rain.'],
            ['difficulty' => 'medium', 'sentence' => 'I’m going to the bookstore, but I don’t know what book to buy yet.'],
            ['difficulty' => 'hard', 'sentence' => 'Although it was raining heavily, they decided to go for a walk. They didn’t want to waste the afternoon.'],
            ['difficulty' => 'hard', 'sentence' => 'The professor explained the theory in great detail. However, many students still found it difficult to understand.'],
            ['difficulty' => 'hard', 'sentence' => 'She had been waiting for the bus for almost an hour. Finally, she decided to call a taxi instead.'],
            ['difficulty' => 'hard', 'sentence' => 'The storm caused significant damage to the town. Yet, the community came together to help rebuild.'],
            ['difficulty' => 'hard', 'sentence' => 'After she finished her lunch, she went to the library. She wanted to study for her upcoming exam.'],
            ['difficulty' => 'hard', 'sentence' => 'He didn’t study for the test. As a result, he was surprised when he scored poorly.'],
            ['difficulty' => 'hard', 'sentence' => 'The movie was entertaining. However, the ending left me feeling unsatisfied.'],
            ['difficulty' => 'hard', 'sentence' => 'I love hiking in the mountains. On weekends, I usually prefer to stay close to home.'],
            ['difficulty' => 'hard', 'sentence' => 'The meeting lasted for several hours. Unfortunately, the final decision was postponed until the next day.'],
            ['difficulty' => 'hard', 'sentence' => 'She had always dreamed of becoming an artist. Therefore, she moved to Paris to pursue her passion.'],
            ['difficulty' => 'hard', 'sentence' => 'They were planning a surprise party for their friend. Unfortunately, she accidentally found out about it.'],
            ['difficulty' => 'hard', 'sentence' => 'The new policy was introduced to improve efficiency. However, it led to unforeseen complications.'],
            ['difficulty' => 'hard', 'sentence' => 'He worked long hours on the project. Despite his efforts, he didn’t meet the deadline.'],
            ['difficulty' => 'hard', 'sentence' => 'The new restaurant in town is very popular. We decided to make a reservation before it gets too crowded.'],
            ['difficulty' => 'hard', 'sentence' => 'They moved to a new city. However, they still miss their old friends from the neighborhood.'],
            ['difficulty' => 'hard', 'sentence' => 'She studied for weeks to pass the final exam. Yet, her anxiety made it difficult to focus during the test.'],
            ['difficulty' => 'hard', 'sentence' => 'Although the sun was shining brightly, the cold wind made it feel much colder. I wasn’t prepared for the temperature drop.'],
            ['difficulty' => 'hard', 'sentence' => 'He wanted to buy a new phone, but he didn’t have enough money. He decided to save up for the next few months.'],
            ['difficulty' => 'hard', 'sentence' => 'She was upset about the results of the survey. She decided to gather more data to support her argument.'],
            ['difficulty' => 'hard', 'sentence' => 'After weeks of preparation, the team was ready for the competition. However, they were still nervous about the outcome.'],
            ['difficulty' => 'hard', 'sentence' => 'They tried to fix the issue with the software. Unfortunately, it continued to malfunction despite their efforts.'],
            ['difficulty' => 'hard', 'sentence' => 'The company announced a major restructure. This caused some employees to feel uncertain about their future.'],
            ['difficulty' => 'hard', 'sentence' => 'The concert was incredible. The crowd cheered loudly for an encore performance.'],
            ['difficulty' => 'hard', 'sentence' => 'Although they had already planned their trip to the beach, the weather forecast predicted rain. They decided to postpone the trip.'],
            ['difficulty' => 'hard', 'sentence' => 'She promised to help her brother with his homework. However, she was distracted by a phone call.'],
            ['difficulty' => 'hard', 'sentence' => 'The city’s public transportation system was unreliable. Many residents preferred to drive instead.'],
            ['difficulty' => 'hard', 'sentence' => 'We had to cancel the picnic because of the storm. We rescheduled it for the following weekend.'],
            ['difficulty' => 'hard', 'sentence' => 'After months of hard work, she finally completed her novel. She was thrilled to have finished it.'],
            ['difficulty' => 'hard', 'sentence' => 'He was an excellent cook, but he had no interest in pursuing it as a career. He preferred to keep it as a hobby.'],
            ['difficulty' => 'hard', 'sentence' => 'She was excited about her new job offer, but she needed some time to think about it. The decision wasn’t easy.'],
            ['difficulty' => 'hard', 'sentence' => 'They had planned the event for weeks, but unexpected circumstances forced them to postpone it. They were disappointed.'],
            ['difficulty' => 'hard', 'sentence' => 'I didn’t know how to fix the car, so I called a mechanic. He arrived an hour later to assist me.'],
            ['difficulty' => 'hard', 'sentence' => 'After completing the project, he felt relieved. However, he knew there was still more work to be done.'],
            ['difficulty' => 'hard', 'sentence' => 'She wanted to go on vacation, but her hectic work schedule made it impossible. She had to postpone her plans.'],
            ['difficulty' => 'hard', 'sentence' => 'The teacher was pleased with the students’ progress, but there was still room for improvement. They continued to work on their skills.'],
            ['difficulty' => 'hard', 'sentence' => 'Although the restaurant had a great reputation, the service was disappointing. I was surprised by the poor experience.'],
            ['difficulty' => 'hard', 'sentence' => 'I didn’t enjoy the movie, but I liked the special effects. They were visually stunning.'],
            ['difficulty' => 'hard', 'sentence' => 'They decided to renovate their house, but the project was delayed several times. It took much longer than expected.'],
            ['difficulty' => 'hard', 'sentence' => 'He worked tirelessly on the project, yet he felt his efforts were unappreciated. It was disheartening.'],
            ['difficulty' => 'hard', 'sentence' => 'After spending hours studying for the exam, she felt confident. However, she still wasn’t sure about some of the questions.'],
            ['difficulty' => 'hard', 'sentence' => 'We ordered the special, but the waiter forgot to bring it to our table. We had to remind him.'],
            ['difficulty' => 'hard', 'sentence' => 'She was looking forward to the weekend, but she still had a lot of work to do. She wasn’t sure if she’d be able to relax.'],
            ['difficulty' => 'hard', 'sentence' => 'The new software was supposed to make our tasks easier. Unfortunately, it turned out to be more complicated than expected.'],
            ['difficulty' => 'hard', 'sentence' => 'He had worked hard to achieve his goals, but he still felt there was more to accomplish. He wasn’t satisfied yet.'],
            ['difficulty' => 'hard', 'sentence' => 'We enjoyed the trip to the museum, though the exhibits were more crowded than we anticipated. It was still a great experience.'],
            ['difficulty' => 'hard', 'sentence' => 'The team practiced for weeks before the game, but they still lost by a large margin. They were disappointed with their performance.'],
            ['difficulty' => 'hard', 'sentence' => 'I wanted to buy a new laptop, but I couldn’t afford it at the time. I decided to wait and save more money.'],
            ['difficulty' => 'hard', 'sentence' => 'Although the meeting was long, it was productive. We made significant progress on the project.'],
            ['difficulty' => 'hard', 'sentence' => 'He hadn’t prepared for the interview, so he felt unprepared when the questions became difficult. It was a stressful experience.'],
            ['difficulty' => 'hard', 'sentence' => 'The event was well-organized, but the turnout was smaller than expected. The organizers were disappointed.'],
            ['difficulty' => 'hard', 'sentence' => 'We had a great time at the park, though we left early because it started to rain. The weather didn’t cooperate.'],
            ['difficulty' => 'hard', 'sentence' => 'The book was interesting, but the ending was disappointing. I had hoped for a better conclusion.'],
            ['difficulty' => 'hard', 'sentence' => 'She found the recipe online, but it turned out to be much more complicated. I decided to try another one.'],
            ['difficulty' => 'hard', 'sentence' => 'After the meeting, they went for lunch. They discussed the next steps for the project.'],
            ['difficulty' => 'hard', 'sentence' => 'She wanted to buy a new car, but her savings weren’t enough to cover the cost. She decided to wait until next year.'],
            ['difficulty' => 'hard', 'sentence' => 'He traveled to several countries during his career, but he always returned to his hometown. It was where he felt most comfortable.'],
            ['difficulty' => 'hard', 'sentence' => 'They decided to take a road trip across the country. Unfortunately, their car broke down halfway through.'],
            ['difficulty' => 'hard', 'sentence' => 'After the concert, they walked around the city. They visited a few museums and enjoyed the atmosphere.'],
            ['difficulty' => 'hard', 'sentence' => 'Although the restaurant had great food, the service was terrible. It really affected the overall experience.'],
            ['difficulty' => 'hard', 'sentence' => 'They had been planning the surprise party for months. Finally, everything was in place.'],
            ['difficulty' => 'hard', 'sentence' => 'She finished writing the letter, but she still hadn’t decided whether to send it. She needed more time.'],
            ['difficulty' => 'hard', 'sentence' => 'The show was entertaining, but it didn’t meet my expectations. I thought it would be more exciting.'],
            ['difficulty' => 'hard', 'sentence' => 'He was focused on his work, but he was also worried about the upcoming presentation. He wasn’t sure if he was ready.'],
            ['difficulty' => 'hard', 'sentence' => 'They managed to fix the issue with the website. However, some users continued to experience difficulties.'],
            ['difficulty' => 'hard', 'sentence' => 'She moved to a new apartment last month. She still hasn’t had time to unpack everything.'],
            ['difficulty' => 'hard', 'sentence' => 'We visited the museum, but the exhibits weren’t as impressive as we had hoped. The experience was underwhelming.'],
            ['difficulty' => 'hard', 'sentence' => 'He made a plan to finish the project by Friday, but he ran into some unexpected challenges. The deadline was quickly approaching.'],
            ['difficulty' => 'hard', 'sentence' => 'After a long day at work, she decided to go for a walk in the park. The fresh air helped clear her mind.'],
            ['difficulty' => 'hard', 'sentence' => 'Although the conference was informative, it was tiring. She felt mentally exhausted by the end of the day.'],
            ['difficulty' => 'hard', 'sentence' => 'He wanted to surprise her with a gift, but he couldn’t find anything she would like. He decided to ask her for suggestions.'],
            ['difficulty' => 'hard', 'sentence' => 'She was excited to start her new job, but she was also nervous about meeting new colleagues. She didn’t know what to expect.'],
            ['difficulty' => 'hard', 'sentence' => 'They had planned a weekend getaway, but a family emergency came up. They had to cancel their trip.'],
            ['difficulty' => 'hard', 'sentence' => 'The team was working hard to meet the deadline. However, there were still many tasks left to complete.'],
            ['difficulty' => 'hard', 'sentence' => 'She practiced the piano every day, but her progress was slower than she had hoped. She needed more time.'],
            ['difficulty' => 'hard', 'sentence' => 'After spending years building their business, they decided to expand internationally. The decision was a major milestone.'],
            ['difficulty' => 'hard', 'sentence' => 'He was excited about the new project, but he was also worried about the workload. He didn’t know if he could handle it.'],
            ['difficulty' => 'hard', 'sentence' => 'The book was well-written, but the plot was predictable. It didn’t offer anything new or surprising.'],
            ['difficulty' => 'hard', 'sentence' => 'They finally reached their destination after a long drive. Despite being tired, they were excited to explore the area.'],
            ['difficulty' => 'hard', 'sentence' => 'She wanted to go shopping for new clothes, but her schedule was too busy. She decided to wait until the weekend.'],
            ['difficulty' => 'hard', 'sentence' => 'The party was lively, but I didn’t know many people. I spent most of the evening by myself.'],
            ['difficulty' => 'hard', 'sentence' => 'Although he enjoyed playing video games, he realized he had spent too much time on them. He decided to cut back and focus on other activities.'],
            ['difficulty' => 'hard', 'sentence' => 'She was eager to start her new project, but she wasn’t sure where to begin. She needed some guidance.'],
            ['difficulty' => 'hard', 'sentence' => 'He had worked hard for years to become a successful entrepreneur. However, he felt like there was always more to accomplish.'],
            ['difficulty' => 'hard', 'sentence' => 'Although they were tired after the long hike, they decided to explore the area. They didn’t want to miss any opportunities.'],
            ['difficulty' => 'hard', 'sentence' => 'The house was small, but it had a cozy atmosphere. They enjoyed spending time together there.'],
            ['difficulty' => 'hard', 'sentence' => 'She had already finished her homework, but she stayed up late studying for the test. She wanted to do well.'],
            ['difficulty' => 'hard', 'sentence' => 'The concert tickets were sold out, but I managed to get a last-minute one. I was relieved.'],
            ['difficulty' => 'hard', 'sentence' => 'The play was captivating, but the final scene was a bit confusing. I had to think about it afterward.'],
            ['difficulty' => 'hard', 'sentence' => 'She enjoyed spending time with her family, but her work often kept her busy. It was difficult to balance both.'],
            ['difficulty' => 'hard', 'sentence' => 'He planned to start exercising regularly, but his schedule kept changing. He found it hard to stick to a routine.'],
            ['difficulty' => 'hard', 'sentence' => 'The book had great reviews, but I found it difficult to get through. It didn’t hold my attention.'],
            ['difficulty' => 'hard', 'sentence' => 'They were excited about their vacation plans. However, they were still unsure about the weather forecast.'],
            ['difficulty' => 'hard', 'sentence' => 'She loved gardening, but the weather wasn’t always favorable. She had to wait for sunny days to plant her flowers.'],
            ['difficulty' => 'hard', 'sentence' => 'After their long flight, they were exhausted. However, they were excited to explore the new city.'],
            ['difficulty' => 'hard', 'sentence' => 'Although they had agreed on the details of the project, there were still some misunderstandings. They had to clarify things.'],
            ['difficulty' => 'hard', 'sentence' => 'She had been looking forward to the concert for weeks. Unfortunately, she caught a cold and couldn’t attend.'],
            ['difficulty' => 'hard', 'sentence' => 'He took a deep breath and dove into the pool. He felt both nervous and excited at the same time.'],
            ['difficulty' => 'hard', 'sentence' => 'The meeting was scheduled for 10 AM, but several people arrived late. They had trouble getting everyone on the same page.'],
            ['difficulty' => 'hard', 'sentence' => 'She knew it would be difficult to find a solution. But she remained determined to try her best.'],
            ['difficulty' => 'hard', 'sentence' => 'They finally solved the problem after hours of work. They were proud of their perseverance.'],
            ['difficulty' => 'hard', 'sentence' => 'He felt nervous about the exam, but he had prepared well. He hoped his efforts would pay off.'],
            ['difficulty' => 'hard', 'sentence' => 'The news spread quickly throughout the office. People were both excited and anxious about the changes.'],
            ['difficulty' => 'hard', 'sentence' => 'After a long day of meetings, he was exhausted. However, he had one more task to complete before going home.'],
            ['difficulty' => 'hard', 'sentence' => 'She wanted to buy a gift for her friend, but she wasn’t sure what to get. She thought about it for a while.'],
            ['difficulty' => 'hard', 'sentence' => 'The event was a huge success, but there were a few hiccups along the way. They were quickly resolved, and everything went smoothly.'],
            ['difficulty' => 'hard', 'sentence' => 'Although he tried his best, he couldn’t finish the book in time. He had hoped to read it before the weekend.'],
            ['difficulty' => 'hard', 'sentence' => 'She loved painting, but she hadn’t had time to pursue it lately. She decided to make time for it soon.'],
            ['difficulty' => 'hard', 'sentence' => 'They had spent months preparing for the wedding. Finally, the big day arrived.'],
            ['difficulty' => 'hard', 'sentence' => 'Although the restaurant served excellent food, the wait time was long. They had to be patient.'],
            ['difficulty' => 'hard', 'sentence' => 'He was worried about the presentation, but he felt more confident once he started speaking. He relaxed as he went along.'],
            ['difficulty' => 'hard', 'sentence' => 'She had a wonderful time at the party, but she felt tired afterward. She decided to leave early.'],
            ['difficulty' => 'hard', 'sentence' => 'They completed the project on time. Nevertheless, they were not satisfied with the final result.'],
            ['difficulty' => 'hard', 'sentence' => 'Although the weather was warm, it was still too cold to go swimming. They decided to wait until the next day.'],
            ['difficulty' => 'hard', 'sentence' => 'He didn’t want to disappoint his family, but he wasn’t sure how to handle the situation. He needed help.'],
            ['difficulty' => 'hard', 'sentence' => 'She loved cooking, but she hadn’t had the chance to try new recipes recently. She planned to experiment more in the future.'],
            ['difficulty' => 'hard', 'sentence' => 'They had a wonderful vacation. However, they couldn’t wait to get back home.'],
            ['difficulty' => 'hard', 'sentence' => 'She planned to visit the art gallery, but she got caught up with work. She had to postpone the visit.'],
            ['difficulty' => 'hard', 'sentence' => 'He spent hours on the project, but he didn’t get the results he expected. He was disappointed.'],
            ['difficulty' => 'hard', 'sentence' => 'The team worked hard to prepare for the event. Nevertheless, things didn’t go as planned.'],
            ['difficulty' => 'hard', 'sentence' => 'He was excited about the new movie, but he didn’t like the ending. It was disappointing.'],
            ['difficulty' => 'hard', 'sentence' => 'They spent the whole day at the amusement park. However, they didn’t get to go on all the rides.'],
            ['difficulty' => 'hard', 'sentence' => 'Although the book was long, it was an enjoyable read. She was glad she finished it.'],
            ['difficulty' => 'hard', 'sentence' => 'He was planning to take a vacation, but he couldn’t find the time. He kept postponing it.'],
            ['difficulty' => 'hard', 'sentence' => 'She decided to take a break from work, but she had too many tasks to complete. She couldn’t relax.'],
            ['difficulty' => 'hard', 'sentence' => 'After a long week at work, he went out to celebrate with his friends. It was a great way to unwind.'],
            ['difficulty' => 'hard', 'sentence' => 'Although she had completed all her assignments, she still felt like she had more to do. She kept herself busy.'],
            ['difficulty' => 'hard', 'sentence' => 'He wanted to buy a new car, but he wasn’t sure which model to choose. He needed more time to decide.'],
            ['difficulty' => 'hard', 'sentence' => 'The movie was entertaining, but the pacing was slow. It could have been more engaging.'],
            ['difficulty' => 'hard', 'sentence' => 'She was looking forward to the weekend, but she had a lot of work to finish. She wasn’t sure if she would have time to relax.'],
            ['difficulty' => 'hard', 'sentence' => 'He knew he had to make a decision, but he couldn’t choose between the two options. It was a tough choice.'],
            ['difficulty' => 'hard', 'sentence' => 'After a long week of work, she was looking forward to a quiet weekend at home. She needed a break.'],
            ['difficulty' => 'hard', 'sentence' => 'The hike was challenging, but the view from the top was worth it. They felt accomplished afterward.'],
            ['difficulty' => 'hard', 'sentence' => 'He was excited about his promotion, but he was also anxious about the new responsibilities. He didn’t know what to expect.'],
            ['difficulty' => 'hard', 'sentence' => 'Although the road trip was fun, they had a few disagreements along the way. They managed to work through them.'],
            ['difficulty' => 'hard', 'sentence' => 'She had been planning the surprise for weeks. She couldn’t wait to see the look on his face.'],
            ['difficulty' => 'hard', 'sentence' => 'After the meeting, they decided to grab lunch together. It was a good way to relax and talk.'],
            ['difficulty' => 'hard', 'sentence' => 'He wanted to surprise his friend with a gift, but he didn’t know what to buy. He was still thinking about it.'],
            ['difficulty' => 'hard', 'sentence' => 'They visited the zoo, but they didn’t see all the animals. The place was crowded.'],
            ['difficulty' => 'hard', 'sentence' => 'She planned to go on a road trip, but she had to cancel it. Something came up.'],
            ['difficulty' => 'hard', 'sentence' => 'The seminar was informative, but I had to leave early. I missed some of the key points.'],
            ['difficulty' => 'hard', 'sentence' => 'He decided to take a break from work, but he found it difficult to relax. He kept thinking about his tasks.']
        ];
        foreach($sentences as $sentence){
            SentenceBuilder::create($sentence);
        }
    }
}
